const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
let state = { live:false, hp:100, ammo:20, reserve:80, magazine:20, money:3400, kills:0, round:17, ct:8, t:8, weapon:'M4A1-S', enemies:3, timer:115, interval:null };
const toast = (message) => { const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(el.timeout); el.timeout=setTimeout(()=>el.classList.remove('show'),1800); };
function sync(){ $('#health').textContent=state.hp; $('#healthBar').style.width=`${state.hp}%`; $('#ammo').textContent=state.ammo; $('#money').textContent=state.money; $('#menuMoney').textContent=state.money; $('#weaponName').textContent=state.weapon; $('#ctScore').textContent=String(state.ct).padStart(2,'0'); $('#tScore').textContent=String(state.t).padStart(2,'0'); $('#round').textContent=String(state.round).padStart(2,'0'); }
function feed(text, type='cyan'){ const p=document.createElement('p');p.innerHTML=`<b style="color:var(--${type})">ROOK</b> ${text}`; $('#killFeed').prepend(p); setTimeout(()=>p.remove(),3600); }
function endRound(win){ state.live=false; clearInterval(state.interval); $('#resultKicker').textContent=win?'ROUND WON':'ROUND LOST'; $('#resultTitle').textContent=win?'SITE SECURED':'MISSION FAILED'; $('#resultText').textContent=win?`${state.kills} raiders neutralized · +$3,250 reward`:'The raiders secured B site.'; if(win){state.ct++;state.money+=3250}else state.t++; sync(); $('#resultScreen').classList.add('show'); }
function tick(){ if(!state.live)return; state.timer--; const m=Math.floor(state.timer/60),s=state.timer%60; $('#roundTimer').textContent=`${m}:${String(s).padStart(2,'0')}`; if(state.timer<=0)endRound(true); else if(Math.random()<.17){ state.hp=Math.max(0,state.hp-(7+Math.floor(Math.random()*10)));sync(); toast('INCOMING FIRE'); if(state.hp<=0)endRound(false); } }
function deploy(){ state.live=true; $('#startScreen').style.display='none'; state.interval=setInterval(tick,1000); sync(); toast('HOLD THE SITE'); }
function fire(enemy){ if(!state.live)return; if(state.ammo<=0){toast('MAGAZINE EMPTY — PRESS R');return}state.ammo--; sync(); $('#hitMarker').classList.remove('show');void $('#hitMarker').offsetWidth;$('#hitMarker').classList.add('show'); enemy.classList.add('dead'); state.kills++;state.enemies--; state.money+=300; state.hp=Math.min(100,state.hp+3); sync(); feed(`eliminated <b>${enemy.dataset.enemy.toUpperCase()}-UNIT</b>`,'orange'); if(state.enemies===0)setTimeout(()=>endRound(true),450); }
function reload(){if(!state.live||state.ammo===state.magazine||!state.reserve)return;toast('RELOADING');setTimeout(()=>{let need=state.magazine-state.ammo,load=Math.min(need,state.reserve);state.ammo+=load;state.reserve-=load;sync();toast('WEAPON READY')},850)}
function buy(card){let cost=Number(card.dataset.cost);if(card.classList.contains('selected'))return;if(state.money<cost){toast('INSUFFICIENT FUNDS');return}state.money-=cost;state.weapon=card.dataset.name;state.ammo=Number(card.dataset.ammo);state.magazine=state.ammo;state.reserve=state.ammo*4;$$('.weapon-card').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');sync();toast(`${state.weapon} EQUIPPED`)}
$('#deploy').onclick=deploy; $$('.enemy').forEach(e=>e.onclick=()=>fire(e)); $('#buyButton').onclick=()=>$('#buyMenu').classList.add('open'); $('#closeBuy').onclick=$('#buyBackdrop').onclick=()=>$('#buyMenu').classList.remove('open'); $$('.weapon-card').forEach(c=>c.onclick=()=>buy(c)); $('#armor').onclick=()=>{if(state.money>=650){state.money-=650;state.hp=100;sync();toast('ARMOR EQUIPPED')}else toast('INSUFFICIENT FUNDS')}; $('#heal').onclick=()=>{if(state.money>=400){state.money-=400;state.hp=Math.min(100,state.hp+35);sync();toast('MEDKIT APPLIED')}else toast('INSUFFICIENT FUNDS')}; $('#helpButton').onclick=()=>toast('CLICK ENEMIES TO FIRE · B LOADOUT · R RELOAD'); $('#nextRound').onclick=()=>{state={...state,live:true,hp:100,ammo:20,reserve:80,magazine:20,kills:0,enemies:3,round:state.round+1,timer:115};$$('.enemy').forEach(e=>e.classList.remove('dead'));$('#resultScreen').classList.remove('show');$('#objectiveProgress').style.width='0';$('#roundTimer').textContent='1:55';sync();state.interval=setInterval(tick,1000);toast('NEW ROUND — DEFEND B SITE')}; document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='b')$('#buyMenu').classList.toggle('open');if(e.key.toLowerCase()==='r')reload();if(e.key==='Escape')$('#buyMenu').classList.remove('open')}); sync();
